hl.bind("PRINT", hl.dsp.exec_cmd("grim -g \"$(slurp)\" \"$(xdg-user-dir PICTURES)/screenshot-$(date +%Y%m%d-%H%M%S).png\""))
hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd("grim \"$(xdg-user-dir PICTURES)/screenshot-$(date +%Y%m%d-%H%M%S).png\""))
hl.bind("SUPER + L", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))
