-- Touchpad gestures
-- Note: 3-finger horizontal workspace switching is built into Hyprland by default.
-- Custom non-conflicting gestures can be registered below:
-- e.g. hl.gesture({ fingers = 4, direction = "vertical", action = "workspace" })
