# Start the desktop shell UI automatically when Hyprland launches.
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = $HOME/.config/quickshell/scripts/system/notification-start
exec-once = $HOME/.config/quickshell/scripts/system/waybar-start
exec-once = $HOME/.config/quickshell/scripts/clipboard/clipboard-start
exec-once = $HOME/.config/quickshell/scripts/wallpaper/hyprpaper-start
exec-once = quickshell --no-duplicate -c rice

ipc = true
splash = true
