# Start the desktop shell UI automatically when Hyprland launches.
exec-once = $HOME/.config/quickshell/scripts/system/waybar-start
exec-once = $HOME/.config/quickshell/scripts/clipboard/clipboard-start
exec-once = $HOME/.config/quickshell/scripts/wallpaper/hyprpaper-start
exec-once = quickshell --no-duplicate -c rice

ipc = true
splash = true
